[theme]
base = "light"

# General color setup
textColor = "#FFFFFFFF"                  # White text
primaryColor = "#60a5fa"
backgroundColor = "#000000ff"
secondaryBackgroundColor = "#292828ff"

# Widgets
showWidgetBorder = true
borderColor = "#000000ff"

# Base text
font = "Inter:https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
baseFontWeight = 400
baseFontSize = 16

# Heading text
headingFont = "Inter:https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
headingFontWeights = [600, 600, 600, 200, 600, 200]
headingFontSizes = ["3rem", "1.5rem", "1rem", "1rem", "0.8rem", "0.8rem"]
